# Generated by Django 4.0 on 2022-04-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_record',
            name='slug',
            field=models.CharField(default=5, max_length=1000),
        ),
    ]
