# Generated by Django 4.0 on 2022-01-20 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mac', '0002_attendance_record_classes_students_delete_features'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classes',
            new_name='Class',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
