# Generated by Django 4.0 on 2022-07-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mac', '0003_alter_attendance_record_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_record',
            name='shared',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
