# Generated by Django 4.0 on 2022-01-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mac', '0003_rename_classes_class_rename_students_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_record',
            name='meet_duration',
        ),
    ]
