# Generated by Django 4.0 on 2022-07-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mac', '0004_attendance_record_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_record',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
