# Generated by Django 4.0 on 2022-10-02 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetCode', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('startTime', models.TimeField()),
                ('stopTime', models.TimeField()),
                ('attendanceData', models.JSONField()),
                ('slug', models.CharField(blank=True, max_length=1000, unique=True)),
                ('shared', models.BooleanField(blank=True, default=False)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
